### ISSUE TITLE
Access to private calendars

### ISSUE THREAD

**Issue by 0xadri** [NacreData/CalVis3#2]
Hi all,

I have been trying to access a private calendar to display it in an internal website.

No success until I realized that the calendar ID was not enough to access the feed that is then used to populate my custom CalVis3 calendar.

What happens is that the calvis-core.js uses the Calendar ID that you specify earlier in the script to access the feed mentioned earlier.

For public calendars this transformation is correct. 
It becomes 'http://www.google.com/calendar/feeds/' + <myCalendarId> + '/public/full'
   ie. http://www.google.com/calendar/feeds/123456789abcdefg%40group.calendar.google.com/public/full

But for private calendars the transformation is different since it needs a calendar ID + a private authentication token
It should become something like 'http://www.google.com/calendar/feeds/' + <myCalendarId> + '/private-' + <token> + '/full'
    ie. http://www.google.com/calendar/feeds/123456789abcdefg%40group.calendar.google.com/private-987654321abcdefg/full

This url that gives you access to the private calendar from an external website can be found in your Calendar settings (Calendar details tab), at the bottom there is a section saying "Private Address", click on the XML icon. It will give you the full URL of the feed. Except that you want to replace (the last word) "basic" by "full". if you then test this url in your browser you should see the feed in an XML format.

I might modify calvis-core.js to implement this private calendar functionality, let me know if you want me to share this with you.

Hope this helps,
adrien

**Comment by 0xadri** [comment]
As a solution I changed line 232 to:

feedUrlArray[i] = [ calIds[i].replace("basic","full") ].join('');

This API now works again with private calendar as well as publics... hooray ! :)

Instead of inserting a calendar ID in the script, just follow the instructions:
1. In your Calendar settings (Calendar details tab), at the bottom there is a section saying "Private Address", click on the XML icon. It will give you the full URL of the feed. 
2. Copy this URL and paste it in your javascript that should be in your calendar page, it's in the OnLoad function, in the line where calIds has values assigned. 
3. It should look something like this:
var calIds = [ 'https://www.google.com/calendar/feeds/<myPrivateCalendarId>/private-<myPrivateCalendarToken>/basic', 'http://www.google.com/calendar/feeds/<myPrivateCalendarId>/private-<myPrivateCalendarToken>/basic' , 'http://www.google.com/calendar/feeds/<myPublicCalendarId>/public/basic'];

It works for me for several calendars, private and public ones.

You might want to read up on Google Calendar feeds here for more fancy features:
http://code.google.com/apis/calendar/data/2.0/developers_guide_protocol.html

Hope this helps,
Adrien

**Comment by NacreData** [comment]
That would be great if you could share it. We'd want to implement it in a
way which makes is easy for the user to choose and mix/match public and
private calendars.

-- devin

On Tue, Apr 19, 2011 at 6:56 AM, adrien-be <
reply@reply.github.com>wrote:

> Hi all,
> 
> I have been trying to access a private calendar to display it in an
> internal website.
> 
> No success until I realized that the calendar ID was not enough to access
> the feed that is then used to populate my custom CalVis3 calendar.
> 
> What happens is that the calvis-core.js uses the Calendar ID that you
> specify earlier in the script to access the feed mentioned earlier.
> 
> For public calendars this transformation is correct.
> It becomes 'http://www.google.com/calendar/feeds/' + <myCalendarId> +
> '/public/full'
>   ie.
> http://www.google.com/calendar/feeds/123456789abcdefg%40group.calendar.google.com/public/full
> 
> But for private calendars the transformation is different since it needs a
> calendar ID + a private authentication token
> It should become something like 'http://www.google.com/calendar/feeds/' +
> <myCalendarId> + '/private-' + <token> + '/full'
>    ie.
> http://www.google.com/calendar/feeds/123456789abcdefg%40group.calendar.google.com/private-987654321abcdefg/full
> 
> This url that gives you access to the private calendar from an external
> website can be found in your Calendar settings (Calendar details tab), at
> the bottom there is a section saying "Private Address", click on the XML
> icon. It will give you the full URL of the feed. Except that you want to
> replace (the last word) "basic" by "full". if you then test this url in your
> browser you should see the feed in an XML format.
> 
> I might modify calvis-core.js to implement this private calendar
> functionality, let me know if you want me to share this with you.
> 
> Hope this helps,
> adrien
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/NacreData/CalVis3/issues/2

## 

http://nacredata.com/devin

**Comment by 0xadri** [comment]
What do you mean by "share it"?
Do you need me to send you the code?

**Comment by NacreData** [comment]
Hi, Yes, I'd be glad to see your code and incorporate it into the
project. You can either send me the code or have it as a fork on
GitHub where I can pull it from. Either will work fine. Glad to see
the project grow.

Thanks!

-- devin

On Mon, May 23, 2011 at 9:51 AM, adrien-be
reply@reply.github.com
wrote:

> What do you mean by "share it"?
> Do you need me to send you the code?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/NacreData/CalVis3/issues/2#comment_1221699

## 

http://nacredata.com/devin

**Comment by 0xadri** [comment]
Cool, will email this to you then. It's in the middle of a mess though so it might take me a wee while to find it.

Cheers,
-adrien

**Comment by 0xadri** [comment]
Hi,
Did you get my email?
-adrien
