### ISSUE TITLE
Does this library work w/ Google Api v3?

### ISSUE THREAD

**Issue by brianzelip** [NacreData/CalVis3#3]
Hi. Does this library work w/ Google Api v3?

**Comment by brianzelip** [comment]
pretty sure it won't since the last commit was years ago. just wondering since I might be interested in using it.

**Comment by NacreData** [comment]
On 21 Jan 2015, at 17:47, Brian Zelip wrote:

> pretty sure it won't since the last commit was years ago.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/NacreData/CalVis3/issues/3#issuecomment-70885463

Yeah, I don't think so. I think they have a more approachable API now 
which should make this less necessary, but I haven't had the time to 
really dig into it. I do have another opportunity upcoming, so thanks 
for reminding me that if there is any extra code needed to make good API 
use with v3 I should post that code.

## devin

contact info: http://nacredata.com/devin

Ask me about Google Apps for Work: hosting your domain-branded email, 
calendar and cloud storage on Google's infrastructure.

**Comment by brianzelip** [comment]
Thanks Devin.
